name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build frontend
      run: npm run build

    - name: Build Tauri application
      run: |    
        cargo build
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all